sbatch hpx_mpi_1node.sh
sbatch hpx_mpi_2node.sh
sbatch hpx_mpi_4node.sh
sbatch hpx_mpi_8node.sh
sbatch hpx_local.sh
sbatch mpi_1node.sh
sbatch mpi_2node.sh
sbatch mpi_4node.sh
sbatch mpi_8node.sh
sbatch mpi_bulk_1node.sh
sbatch mpi_bulk_2node.sh
sbatch mpi_bulk_4node.sh
sbatch mpi_bulk_8node.sh
sbatch mpi_openmp_1node.sh
sbatch mpi_openmp_2node.sh
sbatch mpi_openmp_4node.sh
sbatch mpi_openmp_8node.sh
sbatch openmp.sh
